### PR TITLE
Book event bugs fixed #49 

### LINKED ISSUE #49: Book Event Bugs
- [x] Book an event in a day
- [x] Book an event at a specific time 
- [x] Display event time in bookEvent page

### PR DESCRIPTION
**Pull request by ameentalahmeh**
- [x] Able to Book an event in a day.
- [x] Able to Book an event at a specific time.
- [x] Able to Display event time in `bookEvent` page.

### CODE REVIEW

File: client/src/components/BookEvent/index.js [hunk 1]
```diff
@@ -35,6 +35,7 @@ class BookEvent extends React.Component {
   };
 
   render() {
+    console.log('props',this.props);
```
Comment (shahenazmonia) [inline client/src/components/BookEvent/index.js]: delete console log

Comment (ameentalahmeh) [reply client/src/components/BookEvent/index.js]: done :+1:
